language: node_js
node_js: 
  - "10.15.0"

services:
  - mongodb

cache:
  directories:
    - "node_modules"

before_script:
  - npm run build
  - sleep 15
  - mongo plana_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  
after_success:
  - npm run coverage
